### PR TITLE
feat: zero downtime supported

### LINKED ISSUE #30: Support zero-downtime deployments
Due to the issue in #29 , @strogonoff and I discussed about separating the website upload and website activation phases.

Assume that we have this S3 bucket layout:
```
|--- 20210101000000
       |---  .done
       |--- index.html
       |--- foo
             |--- bar.html
|--- 20210201000000
       |---  .done
       |--- index.html
       |--- foo
             |--- bar.html
|--- 20210301000000
       |---  .done
       |--- index.html
       |--- foo
             |--- bar.html
```

* Each directory (directory = different path, since S3 has no concept of directories) contains a complete website uploaded at a different date.
* We use a Lambda@Edge function to always read the `index.html` from the newest bucket (the directory is named according to the user's preference, e.g. timestamp of initial upload). The `.done` file is created when the bucket is fully uploaded.
* The Lambda@Edge function should be integrated with the function specified in #29 for index path rewrites.

Then the upload flow would be:
1. User uploads complete website to a new path, e.g. `20210401000000/`.
2. Once upload is complete, the user creates `20210401000000/.done`.
3. User runs Cloudfront invalidation on the site. This means that new requests will hit the Lambda@Edge function.
4. A request to `/` hits Lambda@Edge, and the function detects that the newest (sorted latest) directory is `20210401000000` and it also contains the `.done` path.
5. Lambda@Edge returns the S3 file `20210401000000/index.html`.
6. We can have a Lambda function that cleans up previous versions and keep only the latest site with `.done` or the last two copies every hour or every day.

This would be a good way of doing zero-downtime deployments.

Due to the additional complexity of this solution, this might better be a separate terraform module that builds on the current one.

Thoughts @strogonoff @phuonghuynh ?

### PR DESCRIPTION
**Pull request by phuonghuynh**
Resolves https://github.com/riboseinc/terraform-aws-s3-cloudfront-website/issues/30

### CODE REVIEW

**Comment by ronaldtse** [comment]
@phuonghuynh can we use JSON instead of CSV? 😉

**Comment by phuonghuynh** [comment]
yep, but JSON format might be more difficult when appending new record, it need to be parsed to JSON object then append new record; on the other hand, CSV format allow us simply appending new record (new line in order),

**Comment by ronaldtse** [comment]
@phuonghuynh can you help apply this module to https://github.com/glossarist/iev-demo-site ?

The corresponding infrastructure is located in https://github.com/geolexica/infrastructure . Thanks.

**Comment by phuonghuynh** [comment]
ping @ronaldtse for checking AWS deploy account on test site, https://github.com/geolexica/infrastructure

**Comment by ronaldtse** [comment]
@phuonghuynh what exactly do you need? You have access at that account already.

**Comment by phuonghuynh** [comment]
@ronaldtse I got denied error when try to use credentials in IAM outputs, 
```
> Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
        status code: 403, request id: 3a35dff9-0d6d-4de0-9c5e-fbbec6709bfb
```

I also got same error when test with other credentials

**Comment by ronaldtse** [comment]
@phuonghuynh what needs to be further done here? Or can we merge? Thanks.

**Comment by phuonghuynh** [comment]
Yep, we can merge it

**Pull request merged**
